### PR TITLE
Duckdb update 0.10.0 -> 0.10.2

### PR DESCRIPTION
**Pull request by npatsakula**
Hello Antony! I will resolve draft status and tag you when Carlo finish his work, if you don't mind.

- [x] `duckdb` version bump.
- [x] `duckdb-async` version bump.
- [x] `package-lock.json` update.

### CODE REVIEW

**Comment by npatsakula** [comment]
Hello @antonycourtney! Can I ask you to take a look?

**Comment by tjomson** [comment]
Any timeline for when this will be merged?

**Comment by Youssef-Harby** [comment]
It's `0.10.2` now, any updates on that ? Thanks

**Comment by npatsakula** [comment]
> It's `0.10.2` now, any updates on that ? Thanks

Hello @Youssef-Harby! Done.

**Comment by antonycourtney** [comment]
@Youssef-Harby Published about 30 seconds ago.

**Comment by antonycourtney** [comment]
Thanks for the PR @npatsakula and apologies for the delay.

**Comment by nfadili** [comment]
Thanks all!

**Pull request merged**
